# -*- coding: utf-8 -*-
"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at
a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
"""找到新增的字母，实际上是找到字符串中出现频率不同的字母"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        slist = list(s)
        tlist = list(t)
        """
        for i in range(len(slist)):
            if slist[i]!=tlist[i]:
                return tlist[i]
        return tlist[-1]
        """
        for i in set(tlist):
            if tlist.count(i)!=slist.count(i):
                return i

